### PR TITLE
#10 & Codeforces Components Fixes and Enhancements

### LINKED ISSUE #10: Wrong Import Statement That results in crashing.
In `./src/store/reducers/ProblemsReducer.js`

#### Current
``` 
import { problemsCategories } from '../../api/data/problemsData';
```

### Error
Screenshot 2022-02-03 195900

### Correct Import
```
import { problemsCategories } from '../../api/data/ProblemsData';
```

- Would Like to work on It and Contribute More.

### PR DESCRIPTION
**Pull request by Mrhb787**
- Fixed #10 
- Improved `Codeforces` Component UI
- Improved HomePage UI
- Improved Header Navigation UI.
- Added SVG background in Home Page for fast loading. 
- Fixed Typography in `Codeforces` Component

## Before
Screenshot 2022-02-03 215631

## After
Screenshot 2022-02-04 003309
Screenshot 2022-02-04 003230

### CODE REVIEW

**Comment by Mrhb787** [comment]
- Improved Company Table.
### Sample Screen
image

**Comment by Mrhb787** [comment]
- Added Compiler
### Sample Screens
image
image

**Comment by Surya1231** [comment]
Thank you so much for doing this, these are awesome changes and gave a completely new feel to the website.

**Comment by RohitKumar-200** [comment]
Amazing 👏👏👏👏

**Pull request merged**
